[index]
schema_version = 1
generated_at = "2026-03-22T02:46:43Z"
generator = "scripts/generate-index.sh"

[[toolchains]]
family = "gcc"
version = "15.2.0"
status = "active"
license = "GPL-3.0-or-later WITH GCC-exception-3.1"
source_type = "build"
compiler = "g++"
origin = "scrap-release"

[[toolchains]]
family = "llvm"
version = "22.1.0"
status = "active"
license = "Apache-2.0 WITH LLVM-exception"
source_type = "fetch"
compiler = "clang"
origin = "upstream"

[[toolchains.ingots]]
platform = "darwin"
arch = "aarch64"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.0/LLVM-22.1.0-macOS-ARM64.tar.xz"
sha256 = "cd5e615f4dab23d0239359cd343202c5f6ceeaf072c245a3c685d73afac09646"

[[toolchains.ingots]]
platform = "linux"
arch = "aarch64"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.0/LLVM-22.1.0-Linux-ARM64.tar.xz"
sha256 = "e3b4205fe45d5561dec9d46465873a79c26b25b028b310515b38c34f668c6aec"
glibc_version = "2.34"

[[toolchains.ingots]]
platform = "linux"
arch = "x86_64"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.0/LLVM-22.1.0-Linux-X64.tar.xz"
sha256 = "8d662e425e46c48b45f5f970770b5e37f323607c8c2cbc371593fc9c4ba1e7b3"
glibc_version = "2.34"

