[index]
schema_version = 1
generated_at = "2026-03-15T09:59:23Z"
generator = "scripts/generate-index.sh"

[[toolchains]]
family = "llvm"
version = "22.1.0"
status = "active"
license = "Apache-2.0 WITH LLVM-exception"
source_type = "fetch"
compiler = "clang"

[[toolchains.ingots]]
platform = "darwin"
arch = "aarch64"
url = "https://github.com/skipbit/scrap-toolchain/releases/download/llvm-22.1.0/llvm-22.1.0-darwin-aarch64.tar.xz"
sha256 = "59fbeb48477fbeea295cdbe7d3bf40749d200df889325619ac5bd3eebe551ac2"

