[metadata]
schema_version = 1
family = "llvm"
version = "19.1.3"
status = "active"
license = "Apache-2.0 WITH LLVM-exception"
license_files = ["LICENSE.TXT"]
homepage = "https://llvm.org"
description = "LLVM toolchain (Clang, LLD, libc++)"

[metadata.components]
compiler = "clang"

[source]
type = "fetch"
glibc_min = "2.34"
glibc_exclude = ["bin/llvm-exegesis"]

[[source.binaries]]
platform = "linux"
arch = "x86_64"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.3/LLVM-19.1.3-Linux-X64.tar.xz"
sha256 = "052a5ee117782aab5893dba2cdf2cb97c3d873f7a50ba6b1690594161c75c519"

[[source.binaries]]
platform = "linux"
arch = "aarch64"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.3/clang%2Bllvm-19.1.3-aarch64-linux-gnu.tar.xz"
sha256 = "a730175e58233f20a99ecab0015d8cd0f1af5d92411ca1f9e3e472645d889bcd"

[[source.binaries]]
platform = "darwin"
arch = "aarch64"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.3/LLVM-19.1.3-macOS-ARM64.tar.xz"
sha256 = "80a54a467e9e770a76ba9670e89a235224ec47578cc4d4dbd928592813732518"

[test]
hello_world_source = """
#include <iostream>
int main() {
    std::cout << "Hello, scrap!" << std::endl;
    return 0;
}
"""
compile_command = "{compiler}++ -std=c++23 -fuse-ld=lld -o hello hello.cpp"
expected_output = "Hello, scrap!\n"
